# Generated by Django 2.2.7 on 2020-10-16 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Informacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha de pago')),
                ('tipo_pago', models.CharField(choices=[('Inscripción', 'Inscripción'), ('Mensualidad', 'Mensualidad'), ('Uniforme Física', 'Uniforme Física'), ('Playera diaria', 'Playera diaria'), ('Otros', 'Otros')], default='1', max_length=20, verbose_name='Tipo de pago')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Ingrese según formato. Ejemplo: 66.23, 40.00', max_digits=6, verbose_name='Monto a pagar')),
                ('detalle_pago', models.TextField(blank=True, verbose_name='Detalle de inscripcion')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Alumno')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papeleria_completa', models.BooleanField(default=True, help_text='Marque la casila si la papelería está completa', verbose_name='Papeleria completa')),
                ('grado', models.CharField(choices=[('1', 'Primero Básico'), ('2', 'Segundo Básico'), ('3', 'Tercero Básico')], default='1', max_length=1, verbose_name='Grado')),
                ('ciclo', models.CharField(help_text='Ingrese el año sin espacios, ejemplo: 2020', max_length=4, verbose_name='Ciclo de estudio')),
                ('archivo', models.CharField(max_length=2, verbose_name='Nombre del Archivo donde se almacena los documentos')),
                ('gabeta', models.CharField(max_length=2, verbose_name='Nombre de la Gabeta donde se almacenan los documentos')),
                ('folio', models.CharField(max_length=2, verbose_name='Nombre del folio donde se almacenan los documentos')),
                ('detalle', models.TextField(blank=True, max_length=500, verbose_name='Detalle de inscripcion')),
                ('fecha_ins', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha de inscripción')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Alumno')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Informacion',
                'unique_together': {('nombre_alumno', 'ciclo')},
            },
        ),
    ]
