# Generated by Django 2.2.7 on 2020-10-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
    ]
