# Generated by Django 2.2.7 on 2020-10-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0002_auto_20201019_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='detalle_pago',
            field=models.TextField(blank=True, verbose_name='Detalle de pago'),
        ),
    ]
