# Generated by Django 2.2.7 on 2020-10-16 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_encargado', models.CharField(help_text='Ingrese según el formato, primero nombre y luego apellidos. Ejemplo Juan José Pérez García', max_length=40, verbose_name='Nombre completo')),
                ('fecha_nac', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha de nacimiento')),
                ('dpi', models.CharField(help_text='Ingrese los números sin espacio', max_length=13, verbose_name='DPI (número de CUI)')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección de residencia')),
                ('telefono', models.CharField(help_text='Ingrese los números sin espacio', max_length=8, verbose_name='Número de teléfono')),
            ],
            options={
                'verbose_name': 'Encargado',
                'verbose_name_plural': 'Encargados',
                'ordering': ['nombre_encargado'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, help_text='Marque la casilla si el alumno está activo / Deje sin marcar si está inactivo', verbose_name='Estado Activo/Inactivo')),
                ('codigo_personal', models.CharField(max_length=10, verbose_name='Código Personal')),
                ('nombre', models.CharField(help_text='Ingrese según el formato, primero nombre y luego apellidos. Ejemplo Juan José Pérez García', max_length=40, verbose_name='Nombre completo')),
                ('dpi', models.CharField(help_text='Ingrese los números sin espacio', max_length=13, verbose_name='DPI (número de CUI)')),
                ('fecha_nac', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Sexo')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección de residencia')),
                ('telefono', models.CharField(help_text='Ingrese los números sin espacio', max_length=8, verbose_name='Teléfono')),
                ('nombre_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Encargado')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['nombre'],
            },
        ),
    ]
