# Generated by Django 2.2.7 on 2020-10-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo/Inactivo')),
                ('puesto', models.CharField(choices=[('Director', 'Director'), ('Secretaria', 'Secretaria'), ('Conserje', 'Conserje')], default='1', max_length=12, verbose_name='Puesto del trabajador')),
                ('nombre', models.CharField(help_text='Ingrese según el formato, primero nombre y luego apellidos. Ejemplo Juan José Pérez García', max_length=40, verbose_name='Nombre completo')),
                ('dpi', models.CharField(help_text='Ingrese los números sin espacio', max_length=13, verbose_name='DPI (número de CUI)')),
                ('fecha_nac', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=40, verbose_name='Dirección de residencia')),
                ('telefono', models.CharField(help_text='Ingrese los números sin espacio', max_length=8, verbose_name='Telefono')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Otro Puestos',
                'verbose_name_plural': 'Otros Puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo/Inactivo')),
                ('codigo', models.IntegerField(verbose_name='Código del Profesor')),
                ('nombre', models.CharField(help_text='Ingrese según el formato, primero nombre y luego apellidos. Ejemplo Juan José Pérez García', max_length=40, verbose_name='Nombre completo')),
                ('fecha_nac', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha de nacimiento')),
                ('dpi', models.CharField(help_text='Ingrese los números sin espacio', max_length=13, verbose_name='DPI (número de CUI)')),
                ('direccion', models.CharField(max_length=40, verbose_name='Dirección de residencia')),
                ('telefono', models.CharField(help_text='Ingrese los números sin espacio', max_length=8, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['nombre'],
            },
        ),
    ]
