# Generated by Django 2.2.7 on 2020-10-16 21:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Curso', '0001_initial'),
        ('Informacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha')),
                ('ciclo', models.CharField(help_text='Ingrese el año sin espacios, ejemplo: 2020', max_length=4, verbose_name='Ciclo de estudio')),
                ('bimestre', models.IntegerField(help_text='Ingrese el bimestre correspondiente a las notas. Ejemplo: 1, 2, 3, 4', verbose_name='Bimestre')),
                ('nota_tecnologia', models.IntegerField(help_text='Ingrese el numero sin espacios, ejemplos: 04, 32, 54, 89', verbose_name='Nota Tecnologías del Aprendizaje y la Comunicación')),
                ('detalle', models.TextField(blank=True, max_length=500, verbose_name='Detalle de inscripción')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Alumno')),
            ],
            options={
                'verbose_name': 'Tecnologías del Aprendizaje y la Comunicación',
                'verbose_name_plural': 'Tecnologías del Aprendizaje y la Comunicación',
                'ordering': ['nombre_alumno'],
            },
        ),
        migrations.CreateModel(
            name='Productividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha')),
                ('ciclo', models.CharField(help_text='Ingrese el año sin espacios, ejemplo: 2020', max_length=4, verbose_name='Ciclo de estudio')),
                ('bimestre', models.IntegerField(help_text='Ingrese el bimestre correspondiente a las notas. Ejemplo: 1, 2, 3, 4', verbose_name='Bimestre')),
                ('nota_productividad', models.IntegerField(help_text='Ingrese el numero sin espacios, ejemplos: 04, 32, 54, 89', verbose_name='Nota Emprendimiento para la Productividad')),
                ('detalle', models.TextField(blank=True, max_length=500, verbose_name='Detalle de inscripción')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Alumno')),
            ],
            options={
                'verbose_name': 'Emprendimiento para la Productividad',
                'verbose_name_plural': 'Emprendimiento para la Productividad',
                'ordering': ['nombre_alumno'],
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha')),
                ('bimestre', models.IntegerField(help_text='Ingrese el bimestre correspondiente a las notas. Ejemplo: 1, 2, 3, 4', verbose_name='Bimestre')),
                ('nota', models.IntegerField(help_text='Ingrese el numero sin espacios, ejemplos: 04, 32, 54, 89', verbose_name='Nota')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Alumno')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['nombre_alumno'],
            },
        ),
        migrations.CreateModel(
            name='Matematicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha')),
                ('ciclo', models.CharField(help_text='Ingrese el año sin espacios, ejemplo: 2020', max_length=4, verbose_name='Ciclo de estudio')),
                ('bimestre', models.IntegerField(help_text='Ingrese el bimestre correspondiente a las notas. Ejemplo: 1, 2, 3, 4', verbose_name='Bimestre')),
                ('nota_mate', models.IntegerField(help_text='Ingrese el numero sin espacios, ejemplos: 04, 32, 54, 89', verbose_name='Nota Matemáticas')),
                ('detalle', models.TextField(blank=True, max_length=500, verbose_name='Detalle de inscripción')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Alumno')),
            ],
            options={
                'verbose_name': 'Matemáticas',
                'verbose_name_plural': 'Matemáticas',
                'ordering': ['nombre_alumno'],
            },
        ),
        migrations.CreateModel(
            name='Ingles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha')),
                ('ciclo', models.CharField(help_text='Ingrese el año sin espacios, ejemplo: 2020', max_length=4, verbose_name='Ciclo de estudio')),
                ('bimestre', models.IntegerField(help_text='Ingrese el bimestre correspondiente a las notas. Ejemplo: 1, 2, 3, 4', verbose_name='Bimestre')),
                ('nota_ingles', models.IntegerField(help_text='Ingrese el numero sin espacios, ejemplos: 04, 32, 54, 89', verbose_name='Nota Comunicación y Lenguaje, Idioma Extranjero')),
                ('detalle', models.TextField(blank=True, max_length=500, verbose_name='Detalle de inscripción')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Alumno')),
            ],
            options={
                'verbose_name': 'Comunicación y Lenguaje, Idioma Extranjero',
                'verbose_name_plural': 'Comunicación y Lenguaje, Idioma Extranjero',
                'ordering': ['nombre_alumno'],
            },
        ),
        migrations.CreateModel(
            name='Fisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha')),
                ('ciclo', models.CharField(help_text='Ingrese el año sin espacios, ejemplo: 2020', max_length=4, verbose_name='Ciclo de estudio')),
                ('bimestre', models.IntegerField(help_text='Ingrese el bimestre correspondiente a las notas. Ejemplo: 1, 2, 3, 4', verbose_name='Bimestre')),
                ('nota_fisica', models.IntegerField(help_text='Ingrese el numero sin espacios, ejemplos: 04, 32, 54, 89', verbose_name='Nota Educación Física')),
                ('comentario', ckeditor.fields.RichTextField(verbose_name='Comentario sobre el bimestre')),
                ('detalle', models.TextField(blank=True, max_length=500, verbose_name='Detalle de inscripción')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Alumno')),
            ],
            options={
                'verbose_name': 'Educación Física',
                'verbose_name_plural': 'Educación Física',
                'ordering': ['nombre_alumno'],
            },
        ),
        migrations.CreateModel(
            name='Español',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha')),
                ('ciclo', models.CharField(help_text='Ingrese el año sin espacios, ejemplo: 2020', max_length=4, verbose_name='Ciclo de estudio')),
                ('bimestre', models.IntegerField(help_text='Ingrese el bimestre correspondiente a las notas. Ejemplo: 1, 2, 3, 4', verbose_name='Bimestre')),
                ('nota_español', models.IntegerField(help_text='Ingrese el numero sin espacios, ejemplos: 04, 32, 54, 89', verbose_name='Nota Comunicación y Lenguaje, Idioma Español')),
                ('detalle', models.TextField(blank=True, max_length=500, verbose_name='Detalle de inscripción')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Alumno')),
            ],
            options={
                'verbose_name': 'Comunicación y Lenguaje, Idioma Español',
                'verbose_name_plural': 'Comunicación y Lenguaje, Idioma Español',
                'ordering': ['nombre_alumno'],
            },
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha')),
                ('ciclo', models.CharField(help_text='Ingrese el año sin espacios, ejemplo: 2020', max_length=4, verbose_name='Ciclo de estudio')),
                ('bimestre', models.IntegerField(help_text='Ingrese el bimestre correspondiente a las notas. Ejemplo: 1, 2, 3, 4', verbose_name='Bimestre')),
                ('nota_cultura', models.IntegerField(help_text='Ingrese el numero sin espacios, ejemplos: 04, 32, 54, 89', verbose_name='Nota Cultura e Idioma Maya')),
                ('detalle', models.TextField(blank=True, max_length=500, verbose_name='Detalle de inscripción')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Alumno')),
            ],
            options={
                'verbose_name': 'Cultura e Idioma Maya',
                'verbose_name_plural': 'Cultura e Idioma Maya',
                'ordering': ['nombre_alumno'],
            },
        ),
        migrations.CreateModel(
            name='Artistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Ingrese según el formato. Ejemplo: 13/03/2005', verbose_name='Fecha')),
                ('ciclo', models.CharField(help_text='Ingrese el año sin espacios, ejemplo: 2020', max_length=4, verbose_name='Ciclo de estudio')),
                ('bimestre', models.IntegerField(help_text='Ingrese el bimestre correspondiente a las notas. Ejemplo: 1, 2, 3, 4', verbose_name='Bimestre')),
                ('nota_artistica', models.IntegerField(help_text='Ingrese el numero sin espacios, ejemplos: 04, 32, 54, 89', verbose_name='Nota Educación y Expresión Artística')),
                ('detalle', models.TextField(blank=True, max_length=500, verbose_name='Detalle de inscripción')),
                ('nombre_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.Alumno')),
            ],
            options={
                'verbose_name': 'Educación y Expresión Artística',
                'verbose_name_plural': 'Educación y Expresión Artística',
                'ordering': ['nombre_alumno'],
            },
        ),
    ]
